//tealium universal tag - utag.8 ut4.0.201504231016, Copyright 2015 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader,u){try{u=utag.o[loader].sender[id]={}}catch(e){u=utag.sender[id]};u.ev={'view':1};u.qsp_delim="&";u.kvp_delim="=";u.ActivityID="";u.tag_type="conversion";u.Quantity="";u.ProductID="";u.base_url="//bs.serving-sys.com/Serving/ActivityServer.bs?";u.map={"mm_activity_id":"ActivityID"};u.extend=[function(a,b,c,d,e,f,g){d=b['dom.pathname'];if(typeof d=='undefined')return;c=[{'/us/business/cloud-data/index.html':'428105'},{'/us/enterprise/cloud-solutions/deep-security/index.html':'428106'},{'/us/business/cyber-security/index.html':'428107'},{'/us/enterprise/security-risk-management/deep-discovery/index.html':'428108'},{'/us/enterprise/cloud-solutions/secure-cloud/index.html':'428111'},{'/us/technology-innovation/index.html':'428112'},{'/us/enterprise/challenges/advance-targeted-attacks/index.html':'429966'},{'/us/business/switch-to-trend/index.html':'501945'},{'/us/business/complete-user-protection/index.html':'488183'},{'/us/business/have-sales-contact-me/':'563415'},{'/us/business/cloud-data/instant-on-security/':'563414'},{'/us/home/':'488170'},{'/us/business/':'488171'},{'/us/security-intelligence/':'488172'},{'/us/technology-innovation/':'488173'}];var m=false;for(e=0;e<c.length;e++){for(f in c[e]){if(d.toString().indexOf(f)>-1){b['mm_activity_id']=c[e][f];m=true};};if(m)break};if(!m)b['mm_activity_id']='dontrun';},function(a,b){if(b.mm_activity_id=="dontrun")
{return false;}}];u.send=function(a,b,c,d,e,f){if(u.ev[a]||typeof u.ev.all!='undefined'){for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){if(typeof utag_err!='undefined'){utag_err.push({e:'extension error:'+e,s:utag.cfg.path+'utag.'+id+'.js',l:c,t:'ex'})}}};c=[];for(d in utag.loader.GV(u.map)){if(typeof b[d]!='undefined'&&b[d]!=''){e=u.map[d].split(',');for(f=0;f<e.length;f++){u[e[f]]=b[d];}}}
u.rnd=parseInt(Math.random()*1000000);if(u.tag_type=="retargeting"){if(u.TVAL){c.push("CN=DT");c.push("TID="+u.TID);c.push("TVAL="+u.TVAL)}else{c.push("CN=TT");c.push("TID="+u.TID);u.AdvertiserID=u.AdvertiserID||u.ActivityID;c.push("AdvertiserID="+u.AdvertiserID);if(u.TKV1){c.push("TKV1="+u.TKV1)};if(u.TKV2){c.push("TKV2="+u.TKV2);}}
c.push("rnd="+u.rnd);u.head=document.getElementsByTagName("head")[0];u.scr=document.createElement("script");u.scr.type="text/javascript";u.scr.src=u.base_url+c.join(u.qsp_delim);u.head.appendChild(u.scr);}else{c.push("cn=as");c.push("ActivityID="+u.ActivityID);c.push("rnd="+u.rnd);if(u.Session){c.push("Session="+u.Session)};u.OrderID=u.OrderID||b._corder;if(u.OrderID){if(u.Quantity==""&&typeof b._cquan!="undefined"){u.Quantity=0;for(f=0;f<b._cquan.length;f++){u.Quantity+=parseInt(b._cquan[f]);}}
if(u.ProductID==""&&typeof b._cprod!="undefined"){u.ProductID=b._cprod[0];}
u.Value=u.Value||b._csubtotal;c.push("Value="+u.Value);c.push("OrderID="+u.OrderID);c.push("ProductID="+u.ProductID);c.push("ProductInfo="+u.ProductInfo);c.push("Quantity="+u.Quantity);}
d=document.createElement("iframe");d.setAttribute('id','8');d.setAttribute('height','1');d.setAttribute('width','1');d.setAttribute('style','display:none');d.setAttribute('src',u.base_url+c.join(u.qsp_delim));document.body.appendChild(d);}}}
try{utag.o[loader].loader.LOAD(id)}catch(e){utag.loader.LOAD(id)}})('8','trendmicro.nabu');}catch(e){}
